/* Cache only this production app, never API data or other IPQC pages. */
const CACHE='ltc-production-shell-v1';
const directory=new URL('./',self.location.href).pathname;
const isPage=url=>url.origin===self.location.origin&&(url.pathname===directory+'production.html'||(directory==='/'&&url.pathname==='/'));
const key=url=>new Request(url.origin+url.pathname);
self.addEventListener('install',event=>event.waitUntil(self.skipWaiting()));
self.addEventListener('activate',event=>event.waitUntil(self.clients.claim()));
async function cachePage(url,assets=[]){if(!isPage(url))return;const r=await fetch(url.href,{cache:'reload'});if(!r.ok||!r.headers.get('content-type')?.includes('text/html'))return;const cache=await caches.open(CACHE);await cache.put(key(url),r.clone());const html=await r.text();const paths=[...assets,...[...html.matchAll(/<(?:script|link)\b[^>]*\b(?:src|href)=["']([^"']+)["']/g)].map(m=>m[1])].map(p=>new URL(p,url));await Promise.all(paths.filter(u=>u.origin===url.origin&&/\.(?:js|css)$/.test(u.pathname)).map(async u=>{try{const response=await fetch(u.href);if(response.ok)await cache.put(key(u),response);}catch{}}));}
self.addEventListener('message',event=>{if(event.data?.type==='CACHE_PRODUCTION_PAGE')event.waitUntil(cachePage(new URL(event.data.url),Array.isArray(event.data.assets)?event.data.assets:[]).catch(()=>{}));});
self.addEventListener('fetch',event=>{const request=event.request,url=new URL(request.url);if(request.method!=='GET'||url.origin!==self.location.origin||url.pathname.includes('/api/'))return;if(request.mode==='navigate'&&isPage(url)){event.respondWith((async()=>{try{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),4000);try{const response=await fetch(request,{signal:controller.signal});if(!response.ok)throw Error('Page unavailable');if(response.ok&&(response.headers.get('content-type')||'').includes('text/html')){const cache=await caches.open(CACHE);await cache.put(key(url),response.clone());}return response;}finally{clearTimeout(timer);}}catch{const cached=await caches.match(key(url),{cacheName:CACHE});return cached||Response.error();}})());return;}if(url.pathname.includes('/_next/static/')&&['script','style'].includes(request.destination)){event.respondWith((async()=>{const cache=await caches.open(CACHE),cached=await cache.match(key(url));if(cached)return cached;const response=await fetch(request);if(response.ok)await cache.put(key(url),response.clone());return response;})());}});
